---
title: "setup_css"
author: "ML"
date: "1/4/2022"
output: html_document
---

# Load packages
```{r}
library(tidyverse)
library(weights)
```

# Load data

The `collnames` file links campus_id, ACERECODE, and super_opeid.

```{r}
collnames <- read_csv("../../data/collnames.csv")
```

The `college_mobility` file has chetty variables and css variables and tfs matched variables

```{r}
college_mobility <- read_csv("../../data/college_mobility.csv")
```

```{r}
goaltest <- college_mobility |>
  filter(YEAR_TFS > 1995) |> 
  select(campus_id, "GOAL07", "GOAL08_TFS", k_rank)

collnames <- collnames |> 
  select(campus_id, type, tier_name)

goaltest <- left_join(goaltest, collnames)

goaltest <- goaltest |> 
  rename(GOAL_CSS = GOAL07,
         GOAL_TFS = GOAL08_TFS)

write.csv(goaltest, "../../data/matched_goal07.csv", row.names = FALSE)

in_both <- names(goaltest)
#write.csv(in_both, "/users/lawrence/desktop/in_both.csv")

prop.table(table(goaltest$GOAL_TFS,
                 goaltest$GOAL_CSS, exclude = NULL),1)

library(ggthemes)

goaltest |> 
  filter(!is.na(GOAL_TFS), !is.na(GOAL_CSS)) |> 
  group_by(GOAL_TFS) |> 
  count(GOAL_CSS) |> 
  na.omit() |> 
  mutate(prop = n/sum(n)) |> 
  ungroup() |> 
  ggplot(aes(x = GOAL_TFS, y = n, fill = factor(GOAL_CSS))) +
  geom_col() +
  theme_tufte() +
  theme(legend.position = "bottom") +
  geom_text(aes(label = round(prop,2)),
            position = position_stack(vjust = .5))
```

```{r}
tfs_labels <- read_csv("../../data/tfs_question_summary_labels.csv")

tfs_labels <- tfs_labels |> 
  select(Name, Description) |> 
  distinct()

css_labels <- read_csv("../../data/css_question_summary_labels.csv")

css_labels <- css_labels |> 
  select(Name, Description) |> 
  distinct()
```

```{r}
matched_tfs <- college_mobility |> 
  select(ends_with("_TFS")) 

matched_css <- college_mobility |> 
  select(!ends_with("_TFS"))
```

```{r}
css_names <- matched_css |>
  select(starts_with("GOAL"))

goalvars_css <- as.data.frame(names(css_names))

goalvars_css <- rename(goalvars_css, Name = 1)

tfs_names <- matched_tfs |> 
  select(starts_with("GOAL"))

goalvars_tfs <- as.data.frame(names(tfs_names))

goalvars_tfs <- rename(goalvars_tfs, Name = 1)

goalvars_tfs <- goalvars_tfs |> 
  mutate(Name = str_remove(Name, "_TFS"))

goalvars_css <- left_join(goalvars_css, css_labels)
goalvars_css <- goalvars_css |> 
  rename(name_css = Name)

goalvars_tfs <- left_join(goalvars_tfs, tfs_labels)
goalvars_tfs <- goalvars_tfs |> 
  rename(name_tfs = Name)

goal_join <- left_join(goalvars_css, goalvars_tfs)
goal_join <- goal_join |> 
  filter(!is.na(Description)) |> 
  mutate(name_tfs = ifelse(str_detect(Description, "artistic"),
                           "GOAL09", name_tfs))
```


```{r}
css_names <- matched_css |>
  select(starts_with("VIEW"))

viewvars_css <- as.data.frame(names(css_names))

viewvars_css <- rename(viewvars_css, Name = 1)

tfs_names <- matched_tfs |> 
  select(starts_with("VIEW"))

viewvars_tfs <- as.data.frame(names(tfs_names))

viewvars_tfs <- rename(viewvars_tfs, Name = 1)

viewvars_tfs <- viewvars_tfs |> 
  mutate(Name = str_remove(Name, "_TFS"))

viewvars_css <- left_join(viewvars_css, css_labels)
viewvars_css <- viewvars_css |> 
  rename(name_css = Name)

viewvars_tfs <- left_join(viewvars_tfs, tfs_labels)
viewvars_tfs <- viewvars_tfs |> 
  rename(name_tfs = Name)

view_join <- left_join(viewvars_css, viewvars_tfs)
view_join <- view_join |> 
  filter(!is.na(Description)) |> 
  filter(!is.na(name_tfs))
```

```{r}
css_names <- matched_css |>
  select(starts_with("RATE"))

ratevars_css <- as.data.frame(names(css_names))

ratevars_css <- rename(ratevars_css, Name = 1)

tfs_names <- matched_tfs |> 
  select(starts_with("RATE"))

ratevars_tfs <- as.data.frame(names(tfs_names))

ratevars_tfs <- rename(ratevars_tfs, Name = 1)

ratevars_tfs <- ratevars_tfs |> 
  mutate(Name = str_remove(Name, "_TFS"))

ratevars_css <- left_join(ratevars_css, css_labels)
ratevars_css <- ratevars_css |> 
  rename(name_css = Name)

ratevars_tfs <- left_join(ratevars_tfs, tfs_labels)
ratevars_tfs <- ratevars_tfs |> 
  rename(name_tfs = Name)

rate_join <- left_join(ratevars_css, ratevars_tfs)
rate_join <- rate_join |> 
  filter(!is.na(Description)) |> 
  filter(!is.na(name_tfs))
```


